% wam7dofarm_QP_solver - a fast interior point code generated by FORCES
%
%   OUTPUT = wam7dofarm_QP_solver(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.f1 - column vector of length 64
%       PARAMS.lb1 - column vector of length 64
%       PARAMS.ub1 - column vector of length 36
%       PARAMS.C1 - matrix of size [29 x 64]
%       PARAMS.e1 - column vector of length 29
%       PARAMS.f2 - column vector of length 64
%       PARAMS.lb2 - column vector of length 64
%       PARAMS.ub2 - column vector of length 36
%       PARAMS.C2 - matrix of size [15 x 64]
%       PARAMS.e2 - column vector of length 15
%       PARAMS.f3 - column vector of length 64
%       PARAMS.lb3 - column vector of length 64
%       PARAMS.ub3 - column vector of length 36
%       PARAMS.C3 - matrix of size [15 x 64]
%       PARAMS.e3 - column vector of length 15
%       PARAMS.f4 - column vector of length 64
%       PARAMS.lb4 - column vector of length 64
%       PARAMS.ub4 - column vector of length 36
%       PARAMS.C4 - matrix of size [15 x 64]
%       PARAMS.e4 - column vector of length 15
%       PARAMS.f5 - column vector of length 27
%       PARAMS.lb5 - column vector of length 27
%       PARAMS.ub5 - column vector of length 15
%       PARAMS.A5 - matrix of size [12 x 27]
%       PARAMS.b5 - column vector of length 12
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.z1 - column vector of size 36
%       OUTPUT.z2 - column vector of size 36
%       OUTPUT.z3 - column vector of size 36
%       OUTPUT.z4 - column vector of size 36
%       OUTPUT.z5 - column vector of size 15
%
%   [OUTPUT, EXITFLAG] = wam7dofarm_QP_solver(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - Optimal solution has been found (subject to desired accuracy)
%       0 - Maximum number of interior point iterations reached
%      -7 - Line search could not progress
%
%   [OUTPUT, EXITFLAG, INFO] = wam7dofarm_QP_solver(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also LICENSE
